# POST http://localhost:4000/api/client/create
# Content-Type: application/json

# {
#   "firstName": "ZRP",
#   "lastName": "ZRP",
#   "email": "zrp@gmail.com",
#   "role": "admin",
#   "password": "zrp@123"
# }

# POST http://localhost:4000/api/auth/login
# Content-Type: application/json

# {
#   "email": "ruanduarte0300@gmail.com",
#   "password": "Ruan@5995"
# }

# POST http://localhost:3000/api/heroe/create
# Content-Type: application/json

# {
#   "userId": "646cd30c8d787460e20cb09a",
#   "name": "Harvey",
#   "classHeroe": "B",
#   "typeHeroe": "Fire"
# }

# GET http://localhost:4000/api/heroe/list
# Content-Type: application/json

# {
#   "userId": "646cd30c8d787460e20cb09a"
# }

# GET http://localhost:4000/api/threats/getLastThreat
# Content-Type: application/json